//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyStore.Models
{

    using System;
    using System.Collections.Generic;

    public partial class Book
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {

            this.Reviews = new HashSet<Review>();

            this.ShoppingCarts = new HashSet<ShoppingCart>();

            this.OrderDetails = new HashSet<OrderDetail>();

        }


        public int BookID { get; set; }

        public int CategoryID { get; set; }

        public string BookTitle { get; set; }

        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }

        public decimal Price { get; set; }


        public string Image { get; set; }

        public Nullable<int> PublishYear { get; set; }

        public Nullable<int> Stock { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Review> Reviews { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    }

}